# Site settings
title: Stuart Philp
email: contact@stuartphilp.com
description: > # this means to ignore newlines until "baseurl:"
  A blog by Stuart Philp. Web, Quality, DevOps, Software Development, Engineering Management
baseurl: ""
url: "http://stuartphilp.com"
twitter_username: stuartphilp
github_username:  stuartphilp
linkedin_username:  stuartphilp
facebook_username:  stuart.w.philp

# Build settings
markdown: kramdown
